web:
  build: .
  volumes:
    # make sure to mount your htdocs as /var/www/html, for example:
    # - /c/Users/username/htdocs:/var/www/html
  environment:
      XDEBUG_CONFIG: remote_host=192.168.99.1
  ports:
    - "80:80"
    - "443:443"